version: '2'
services:
    gradlereact-app:
        image: gradlereact
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gradlereact-postgresql:5432/gradleReact
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gradlereact-postgresql:
        extends:
            file: postgresql.yml
            service: gradlereact-postgresql
